name: Install dependencies
description: Install Node.js and pnpm dependencies

runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v6
      with:
        version: 11
    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version-file: package.json
        cache: pnpm
    - name: Install pnpm dependencies
      run: pnpm ci
      shell: bash
