name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Clone the repository
        uses: actions/checkout@v7
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Test units with Vitest
        run: pnpm run test

  e2e:
    runs-on: ubuntu-latest
    name: E2E tests
    steps:
      - name: Clone the repository
        uses: actions/checkout@v7
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Test end-to-end with Vitest and Verdaccio
        run: pnpm run e2e

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Clone the repository
        uses: actions/checkout@v7
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Build with tsup
        run: pnpm run build

  typecheck:
    runs-on: ubuntu-latest
    name: Type checks
    steps:
      - name: Clone the repository
        uses: actions/checkout@v7
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Compile with TypeScript
        run: pnpm run typecheck

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Clone the repository
        uses: actions/checkout@v7
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Static analysis with ESLint
        run: pnpm run lint

  format:
    runs-on: ubuntu-latest
    name: Formatting
    steps:
      - name: Clone the repository
        uses: actions/checkout@v7
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Check formatting with Prettier
        run: pnpm run format:check
